### ISSUE TITLE
Arms error last update 11/18/2019

### ISSUE THREAD

**Issue by ByKyTa** [Kxnrl/CSGO-ArmsFix#10]
![image](https://user-images.githubusercontent.com/33537916/69333459-3bb61e80-0c8b-11ea-845e-aae2f1c4c37b.png)

**Comment by Kxnrl** [comment]
https://forums.alliedmods.net/showthread.php?p=2673834

**Comment by ByKyTa** [comment]
Sorry, I don't understand this very well, could you please tell me what to do? @Kxnrl

**Comment by Kxnrl** [comment]
https://github.com/Kxnrl/sm-ext-ArmsFix 
try this
